### PR TITLE
Fixes for 6 axis

### PR DESCRIPTION
**Pull request by bilsef**
Fixed some typos and made some improvements

### CODE REVIEW

**Comment by bilsef** [comment]
Here is the configuration I used to test this (on a Teensy 3.6 board).

[6axisConfig.zip](https://github.com/DerAndere1/Marlin/files/5235282/6axisConfig.zip)

**Comment by bilsef** [comment]
Changes to types.h fix issue #7

**Comment by DerAndere1** [comment]
Thanks, I suspected types.h as the cause for this longstanding bug, but as you might know, code review can be more challenging than writing new code at times. So your fix is a massive help. Thanks a lot for digging into this!

**Comment by DerAndere1** [comment]
I in my PR, I reverted your changes in Configuration.h because they were exposing the user to the non-standard macro `LIST_N(N, V, ...)` which might cause confusion and is probably not accepted by the maintainer of upstream MarlinFirmware (although I will use your style in my personal config file). Also, it is better to assume that the IJK axes are setup like the Z axis (with a lead screw) so default max feedrates and -accelerations should be similar to those for the Z axis. Using the same default values as for XYZ may cause hardware damage if users with lead screws forget to adjust the values.

**Comment by bilsef** [comment]
@DerAndere1, Sounds good.  I will continue to work on other issues.

**Pull request merged**
