### PR TITLE
Add SKR_PRO Spindle Support and fix M17

### PR DESCRIPTION
**Pull request by FNeo31**
Add SKR_PRO Spindle-Laser Support and fix M17

Change from AXIS4_STR to AXIS4_NAME to be possible compile

I'll Test on Machine

### CODE REVIEW

**Comment by FNeo31** [comment]
@DerAndere1 please add to you branch to be possible continue the tests to implement in main Marlin

**Comment by DerAndere1** [comment]
Thanks. I added a commit with your fix for M17, with you as author: https://github.com/DerAndere1/Marlin/commit/75587dff5057e28c28463539597b469a852d91f9. But I prefer not to change any pin files . Those changes should go into a seperate pull request targeted at upstream MarlinFirmware bugfix-2.0.x branch. In case you wonder how you can test with your modified pins file: When I personally test in hardware, I always have one local branch (e.g. called 6axis_PR1) that is based on https://github.com/DerAndere1/Marlin/tree/6axis_PR1 and that I only use for updating my local code. I never  change the 6axis_PR1 branch directly. I rather have a test_x branch that is based on my local, pristine  6axis_PR1 branch. I add my own modified config files and pin files only to the test_x branch. 
When the remote https://github.com/DerAndere1/Marlin/tree/6axis_PR1 branch is updated, you can then checkout your local 6axis_PR1 branch and `git pull` the changes. Then `checkout` your test_x branch and `rebase` your test_x branch onto the updated  6axis_PR1 branch. 

If you have problems with synchronizing your code with mine, let me know. I can guide you. Can we close this pull request?

Cheers

**Comment by FNeo31** [comment]
The pins in SKR PRO I just add the IJ axis pins, spindle laser pins, and i2C memory. Don't have other pin changes this is why I send it for pull request, but ok I will just pull corrections to be easier for you

**Comment by FNeo31** [comment]
Yes, can close it, I'll try to test tomorrow on my machine. About the 5 axis I will try to make by you way, I check 2 things that wasn't possible to compile, putting just the 4 and 5 axis on uart with TMC2209. Didn't enable the serials for just this axis, I didn't have time to check where's the problem, but if you could check it whould be nice

**Comment by DerAndere1** [comment]
I added some Trinamic TMC related fixes to my 6axis_PR1 branch today.

**Comment by DerAndere1** [comment]
Support for canned drilling cycles was removed from the PR1 branch with commit https://github.com/MarlinFirmware/Marlin/pull/19112/commits/3721ab1f7e332bb8bd4778209e7695ea96ea6ce3 . I think thinkyhead wants to first merge 6 axis support and then we can add the canned drilling cycles seperately. But you can easily add the feature back by reverting the mentioned commit (add back all sections marked in red in the linked commit).

**Comment by FNeo31** [comment]
Yes, the drilling cycles it's in 1 file and is just adding on gcode parser, so it's easy to put it again, I agree with thinkyhead, at first put the 6 axis working with all features and after that I want to make the 5axis calibration feature to be easier the configuration of the 5 axis on a CNC machine

**Comment by FNeo31** [comment]
I test your branch on my machine

At first, wasn't possible to compile with TMC2209 In UART on just on the Axis I and Axis J

The Z max limit on LCD moving manually gets the max of  Axis I (see video)

Another thing that happens and I didn't solve, and I don't know how to solve it is the EEPROM and the connection with the LCD in serial mode.
The EEPROM send the error on the image, and I reset  and test to save and load and gave this error. Can you help? 

IMG_20210608_132302

https://user-images.githubusercontent.com/37299777/121231491-60cbab80-c888-11eb-9e6c-1baf3f1a61d7.mp4

**Comment by DerAndere1** [comment]
Uh. Thanks for the Report!  Can you test current MarlinFirmware/Marlin branch bugfix-2.0.x? 6axis Support was Merged into it recently and now my 6axis_PR1 branch ist outdated. If you have already made Changes, please Send me a link to your branch. then I can help you rebasing your changes onto MarlinFirmware/Marlin bugfix-2.0.x . At the minimum I Would Need your Config Files and your pins_SKR_PRO.h file to be able to help.

**Comment by FNeo31** [comment]
I will try to check in the base Marlin and I will test it today, and I will report you. 
The LCD doesn't work without extruders I test and out a dummy extruder and worked well in LCD, is a problem from LCD that is just programed for 3D printer so assume that have 1 extruder everytime and they check if it's connected to the machine by the temperature report

**Comment by FNeo31** [comment]
On Marlin/bugfix all work good except without extruders (but I add 1 and it's working)

Individual homing menu didn't compile. I change from "I_STR" to "AXIS4_STR" and make a commit to bugfix branch.

I test on machine and work well in the first test

I will add the drilling cycles on my branch

**Comment by DerAndere1** [comment]
You can set fake temperature values with some settings in Configuration.h, then maybe EXTRUDERS 0 works at least when sending G-code from a host software via USB: Change
```
#define TEMP_SENSOR_0 1
```
to
```
#define TEMP_SENSOR_0 999
```
and maybe increase the value of
```
#define DUMMY_THERMISTOR_999_VALUE 100
```

**Comment by FNeo31** [comment]
Didn't work I made a workaround. My setup is SKR PRO v1.1 and Btt TFT7.0 so to test all the features I put the LCD connection like CR10 for just 1 cable and said to Marlin that I have Btt expansion board and moved the E0 for the expansion board, and of course I put the thermistor 999 and 200deg

**Pull request closed without merging**
